plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "BruceWanShuang"
email: wanshuang@yahoo.com
description: ""
github:
  username: BruceWanShuang
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
comment:
    repo: 首页
    client_id: a6fb73b3e790e234bab8
    client_secret: cc10aaff53a03d05ab2ee002dbf401dd7627c7a3

url: "https://brucewanshuang.github.io/"
imgrepo: "https://brucewanshuang.github.io/"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

